"""Generate an outbound NDA from the draft-ui intake.

POST /api/generate-nda is what the Generator tab's "Generate NDA" button calls.
It maps the intake payload to the generation engine, produces a Playbook-passing
NDA from the chosen signing entity + the company template, creates a matter for
it, and registers the generated document as a tracked ``generated`` artifact.

The endpoint is intentionally thin: all the substance (template fill, Playbook-
bounded AI clause adaptation, the self-check) lives in ``nda_generation``. Here
we validate the payload, drive the engine, and shape the response draft-ui needs.
"""

from __future__ import annotations

import datetime
from typing import Any
from urllib.parse import quote

from .. import nda_generation, telemetry
from ..nda_generation import CounterpartyIntake, NdaGenerationError
from .common import request_owner_user_id


def handle_generate_nda(handler) -> None:
    telemetry.increment("generate_nda_requests")
    payload = handler._read_json_payload()
    if payload is None:
        return

    try:
        entity_id, intake, governing_law_override = _intake_from_payload(payload)
    except _PayloadError as error:
        handler._send_json({"error": str(error)}, status=400)
        return

    owner_user_id = request_owner_user_id(handler)

    try:
        result, matter, artifact = _generate(
            entity_id, intake, owner_user_id=owner_user_id, governing_law_override=governing_law_override
        )
    except NdaGenerationError as error:
        # Unknown entity, unapproved governing law, malformed template, an
        # unsupported posture (one-way) — client-correctable input errors — OR the
        # hard safety gate refusing an off-position draft. All surface as 400 with a
        # clear message and NEVER return the document; the safety-gate trip gets its
        # own telemetry signal so a drifting AI is visible in the metrics.
        if str(error).startswith(nda_generation.SAFETY_GATE_MESSAGE):
            telemetry.increment("generate_nda_safety_gate_blocked")
        else:
            telemetry.increment("generate_nda_rejected")
        handler._send_json({"error": str(error)}, status=400)
        return
    except Exception as error:  # noqa: BLE001 - surface engine failure as 500, don't leak a stack
        telemetry.increment("generate_nda_failed")
        handler._send_json({"error": f"NDA generation failed: {error}"}, status=500)
        return

    # The self-check is advisory in the response (the engine already passes the
    # Playbook deterministically); surfacing it lets the UI flag a rare miss.
    check = nda_generation.self_check_generated_nda(result.docx_bytes, playbook=None)

    telemetry.increment("generate_nda_succeeded")
    matter_id = str(matter.get("id") or "")
    handler._send_json(
        {
            "matter_id": matter_id,
            "artifact_id": str(getattr(artifact, "id", "") or ""),
            "status": "generated",
            # The generated .docx is the matter's source document, downloadable
            # over the existing matter-source GET route (draft-ui can also route
            # the matter_id straight into the matter detail view).
            "download_url": f"/api/matters/{quote(matter_id, safe='')}/source" if matter_id else "",
            "self_check": {
                "passed": check.passed,
                "overall_status": check.overall_status,
                "native_failures": check.native_failures,
                "dynamic_failures": check.dynamic_failures,
            },
            "manifest": result.manifest.to_dict(),
        },
        status=201,
    )


def _generate(entity_id: str, intake: CounterpartyIntake, *, owner_user_id: str, governing_law_override: str = ""):
    """Generate, create the matter from the generated bytes, save the artifact.

    The generated NDA becomes the matter's document (the matter is created from
    its bytes, which also runs the review + auto-registers an ``original``
    artifact), and the same bytes are then registered as the ``generated``
    artifact with the entity as actor and lineage back to that original.
    """

    from ..ingestion_service import create_matter_from_document  # noqa: PLC0415
    from ..artifact_registry import ROLE_ORIGINAL, latest_artifact_for_role  # noqa: PLC0415
    from ..matter_repository import DiskMatterRepository  # noqa: PLC0415

    repository = DiskMatterRepository()
    result = nda_generation.generate_nda_for_entity(
        entity_id, intake, governing_law_override=governing_law_override
    )

    # HARD safety gate on the ACTUAL ship path, BEFORE any persistence: a generated
    # NDA that fails its own Playbook or carries a prohibited position must never
    # become a matter/artifact. Raises NdaGenerationError (-> 4xx) so the endpoint
    # returns a "safety gate" error and never the unsafe document. (The per-clause
    # adapter guard can fall back to deterministic wording; this whole-doc gate is
    # the final backstop, and it must live here because the route builds the matter
    # + artifact itself rather than going through generate_and_save_nda.)
    nda_generation.assert_generated_nda_is_on_position(result)

    filename = _generated_filename(intake, result)
    matter = create_matter_from_document(
        filename=filename,
        document_bytes=result.docx_bytes,
        source_type="generated",
        board_column="generated",
        intake_metadata={"generation": result.manifest.to_dict()},
        owner_user_id=owner_user_id,
        repository=repository,
        # Defer the AI review: this NDA was just generated from our own playbook and
        # already passed the safety gate above, so create the matter with the fast
        # deterministic review and let the AI review run on-demand (Refresh Review).
        # This is the slow step we're skipping at generation time.
        defer_ai_review=True,
    )

    original = latest_artifact_for_role(matter, ROLE_ORIGINAL)
    artifact = nda_generation.save_generated_nda(
        result,
        str(matter.get("id") or ""),
        repository=repository,
        based_on_artifact_id=(original.id if original else ""),
        owner_user_id=owner_user_id,
    )
    return result, matter, artifact


def _generated_filename(intake: CounterpartyIntake, result: nda_generation.GenerationResult) -> str:
    counterparty = (intake.company_name or "Counterparty").strip()
    safe = "".join(ch if ch.isalnum() or ch in " -_" else "" for ch in counterparty).strip() or "Counterparty"
    return f"NDA - {safe}.docx"


class _PayloadError(ValueError):
    """A client payload problem (missing/invalid field)."""


def _intake_from_payload(payload: dict[str, Any]) -> tuple[str, CounterpartyIntake, str]:
    """Map the draft-ui Generate payload to (entity_id, intake, govlaw_override).

    Two payload shapes are accepted so the route is robust to how draft-ui wires
    the form (the field names were settled by message, but we tolerate both the
    flat and the nested intake shape, plus the obvious aliases):

        {signing_entity_id, intake:{counterparty_name, project, term_years,
         nda_type, ...}, governing_law_override?}
        {signing_entity:{id}, counterparty:{name,...}, project_purpose, term,
         nda_type, notes, effective_date}

    ``governing_law_override`` is an optional Playbook governing-law option id
    (india | delaware | england_and_wales | difc): when set, the draft uses that
    (still approved) law instead of the entity default. The engine rejects an
    UNAPPROVED override with NdaGenerationError -> 400; an empty/absent value
    keeps the entity's registered law.
    """

    if not isinstance(payload, dict):
        raise _PayloadError("Request body must be a JSON object.")

    governing_law_override = _governing_law_override_from_payload(payload)

    entity_id = _entity_id_from_payload(payload)
    if not entity_id:
        raise _PayloadError("A signing entity must be selected.")

    # The intake fields may arrive nested under "intake" or at the top level;
    # counterparty identity may arrive nested under "counterparty" or flat.
    intake_block = payload.get("intake") if isinstance(payload.get("intake"), dict) else {}
    counterparty = payload.get("counterparty") if isinstance(payload.get("counterparty"), dict) else {}

    def field(*keys: str) -> str:
        """First non-empty string value across the intake block, counterparty
        block, and top-level payload, for any of the given aliases."""
        for source in (intake_block, counterparty, payload):
            for key in keys:
                value = source.get(key)
                if isinstance(value, str) and value.strip():
                    return value.strip()
        return ""

    company_name = field("counterparty_name", "name")
    if not company_name:
        raise _PayloadError("The counterparty name is required.")

    nda_type = field("nda_type") or nda_generation.NDA_TYPE_MUTUAL

    intake = CounterpartyIntake(
        company_name=company_name,
        registered_office=field("counterparty_registered_office", "registered_office"),
        jurisdiction_of_incorporation=field(
            "counterparty_jurisdiction", "jurisdiction_of_incorporation"
        ),
        business_description=field("business_description", "notes"),
        purpose=field("project", "project_purpose", "purpose")
        or "the proposed business relationship between the parties",
        term_years=_term_years(_first(intake_block, payload, "term_years", "term")),
        nda_type=nda_type,
        agreement_date=_agreement_date(_first(intake_block, payload, "effective_date", "agreement_date")),
    )
    return entity_id, intake, governing_law_override


def _entity_id_from_payload(payload: dict[str, Any]) -> str:
    """Resolve the signing entity id from either the flat or the nested shape."""
    flat = payload.get("signing_entity_id")
    if isinstance(flat, str) and flat.strip():
        return flat.strip()
    signing_entity = payload.get("signing_entity")
    if isinstance(signing_entity, dict):
        nested = signing_entity.get("id")
        if isinstance(nested, str) and nested.strip():
            return nested.strip()
    return ""


def _governing_law_override_from_payload(payload: dict[str, Any]) -> str:
    """Resolve the chosen governing-law option id from the payload.

    The committed FE (buildDraftPayload) carries the chosen law INSIDE the
    signing-entity bundle as ``signing_entity.governing_law.playbook_option_id``
    (always present — the effective law, override or not). We pass it through as
    the engine's ``governing_law_override``; the engine treats a value equal to
    the entity default as a no-op, so always forwarding the chosen law is correct
    and keeps the server authoritative on the overridden flag. A flat
    ``governing_law_override`` / top-level ``governing_law`` block is also accepted
    (test + alternate-client robustness). An unapproved id is rejected downstream
    (NdaGenerationError -> 400)."""
    # Preferred: the FE's nested signing_entity.governing_law.playbook_option_id.
    signing_entity = payload.get("signing_entity")
    if isinstance(signing_entity, dict):
        option_id = _option_id_from_law_block(signing_entity.get("governing_law"))
        if option_id:
            return option_id
    # Fallbacks: a flat override string or a top-level governing_law block.
    flat = payload.get("governing_law_override")
    if isinstance(flat, str) and flat.strip():
        return flat.strip()
    return _option_id_from_law_block(payload.get("governing_law"))


def _option_id_from_law_block(block: object) -> str:
    """Pull the playbook_option_id (or id) out of a governing_law block."""
    if isinstance(block, dict):
        option_id = block.get("playbook_option_id") or block.get("id")
        if isinstance(option_id, str) and option_id.strip():
            return option_id.strip()
    return ""


def _first(*sources_then_keys: Any) -> object:
    """Return the first present value for any of the trailing keys across the
    leading dict sources. Keys are the string args; sources are the dict args."""
    sources = [s for s in sources_then_keys if isinstance(s, dict)]
    keys = [k for k in sources_then_keys if isinstance(k, str)]
    for source in sources:
        for key in keys:
            if key in source and source.get(key) not in (None, ""):
                return source.get(key)
    return None


def _term_years(value: object) -> int:
    """Coerce a term to an int year count (the engine caps it to the Playbook max)."""

    if value is None or value == "":
        return 2
    try:
        return int(str(value).strip().split()[0])
    except (ValueError, IndexError):
        return 2


def _agreement_date(value: object) -> datetime.date | None:
    text = str(value or "").strip()
    if not text:
        return None
    try:
        return datetime.date.fromisoformat(text)
    except ValueError:
        return None
